version: "3.7"
services:
  php-fpm:
    image: hello-docker-compose-file-variable_php-fpm:${TAG:-development}
    build:
      context: api
      dockerfile: development.dockerfile
      target: ${TARGET:-development}
    volumes:
      - ./api:/usr/local/app/hello-docker-compose-file-variable